version: '3.8'

services:
    app:
        build:
            context: ../
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ../:/var/www/html
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_web
        working_dir: /var/www/html
        volumes:
            - ../:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:12
        container_name: laravel_db
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

networks:
    laravel:

volumes:
    pgdata:
